name: "Video-client"
description: "Clioent for video-addon"
version: "1.0.5"
slug: "video-client"
init: false
arch:
  - aarch64
  - amd64
startup: services
#ports:
#  8000/tcp: 8080
#  9123/tcp: 9123
#  3030/tcp: 3030
device_id: "abcde"
hassio_api: true
host_dbus: true
host_network: true
# Hvis ingress er nødvendigt